[tool.ruff]
# Comprimento da linha
line-length = 88
target-version = "py310"

[tool.ruff.lint]
# E: Erros de estilo (Pycodestyle)
# F: Erros lógicos (Pyflakes)
# I: Ordenação de imports (Isort)
select = ["E", "F", "I"]

[tool.coverage.run]
# Medir cobertura de todo o diretório atual
source = ["."]
# Não medir cobertura dos próprios testes ou de pastas virtuais
omit = [
    "tests/*",
    "venv/*",
    ".venv/*",
    "setup.py"
]

[tool.coverage.report]
# Mostra no terminal quais linhas não foram testadas
show_missing = true
# O pipeline FALHA se a cobertura for menor que 80%
fail_under = 80

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true